const run = () => {
  throw new Error("this is error");
};

run();
